image:
  file: ./Dockerfiles/dockerfile-firefox
ports:
#- port: 3000
- port: 6901
  onOpen: ignore
- port: 5901
  onOpen: ignore
#tasks:
#- init: yarn
#  command: 
github:
  prebuilds:
    pullRequestsFromForks: true
