image:
  file: ./Dockerfiles/dockerfile-firefox
ports:
- port: 3000
- port: 6080
  onOpen: ignore
- port: 5900
  onOpen: ignore
#tasks:
#- init: yarn
#  command: 
github:
  prebuilds:
    pullRequestsFromForks: true
