FROM gitpod/workspace-full-vnc:latest

USER root
# Install nodejs.
RUN apt-get update \
    && apt-get install node \
    && apt-get clean \
    && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
